sudo: required

services:
  - docker

before_install:
  - docker build -t excel61/docker-react2 -f Dockerfile.dev .
script:
  - docker run excel61/docker-react2 npm test 
after_success:
  - docker build -t excel61/docker-react2 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push excel61/docker-react2

