language: node_js
node_js:
  - "12"
sudo: required

services:
  - docker

before_install:
  - docker build -t excel61/docker-react-test -f Dockerfile.dev .
script:
  - docker run excel61/docker-react-test npm test 
  - docker build -t excel61/docker-react2 .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push excel61/docker-react2

